# Generated by Django 3.2.7 on 2021-10-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
